### ISSUE TITLE
コミットハッシュ指定で起動できない

### ISSUE THREAD

**Issue by tamaina** [Srgr0/misskey-test-ga#7]
謎

![image](https://github.com/joinmisskey/misskey-tga/assets/7973572/2af898a5-7108-4277-a7c6-8a77046bd682)

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/actions/runs/7845454011/job/21409910374

**Comment by tamaina** [comment]
![image](https://github.com/joinmisskey/misskey-tga/assets/7973572/b6b445a6-4e80-4c41-8b4e-936dcb92fdff)

これか原因は

**Comment by Srgr0** [comment]
bash-install側でコミットハッシュの指定を想定していなかったことが原因です。
この問題は以下のコミットにおいて修正されました。
[3c999ddbc7f44685c247db0d60d7b73ccfcbb6d6](https://github.com/joinmisskey/bash-install/commit/3c999ddbc7f44685c247db0d60d7b73ccfcbb6d6)
